In [1]:
import os

In [2]:


#!pip3 install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html



In [3]:
import pandas as pd

In [4]:
os.chdir("liar_plus_dataset/")

In [5]:
os.getcwd()

'E:\\Project\\liar_plus_dataset'

In [6]:
columns = ['id_json', 'label', 'statement', 'subject', 
 'speaker', 'speaker_job', 'state', 'party', 
 'barely_true_counts', 'false_counts', 'half_true_counts',
 'mostly_true_counts', 'pants_on_fire_counts', 'context', 'justification']

In [7]:
train_data = pd.read_csv("train2.tsv", sep='\t', header=None, index_col=0, names=columns)
val_data = pd.read_csv('val2.tsv', sep='\t', header=None, index_col=0, names=columns)
test_data = pd.read_csv('test2.tsv', sep='\t', header=None, index_col=0, names=columns)

In [8]:
train_data.set_index('id_json',inplace=True)
val_data.set_index('id_json',inplace=True)
test_data.set_index('id_json',inplace=True)

In [9]:
train_data.head()

label                                          statement  \
id_json                                                                      
2635.json         false  Says the Annies List political group supports ...   
10540.json    half-true  When did the decline of coal start? It started...   
324.json    mostly-true  Hillary Clinton agrees with John McCain "by vo...   
1123.json         false  Health care reform legislation is likely to ma...   
9028.json     half-true  The economic turnaround started at the end of ...   

                                       subject         speaker  \
id_json                                                          
2635.json                             abortion    dwayne-bohac   
10540.json  energy,history,job-accomplishments  scott-surovell   
324.json                        foreign-policy    barack-obama   
1123.json                          health-care    blog-posting   
9028.json                         economy,jobs   charlie-crist   

                     speaker_job     state       party  barely_true_counts  \
id_json                                                                      
2635.json   State representative     Texas  republican                 0.0   
10540.json        State delegate  Virginia    democrat                 0.0   
324.json               President  Illinois    democrat                70.0   
1123.json                    NaN       NaN        none                 7.0   
9028.json                    NaN   Florida    democrat                15.0   

            false_counts  half_true_counts  mostly_true_counts  \
id_json                                                          
2635.json            1.0               0.0                 0.0   
10540.json           0.0               1.0                 1.0   
324.json            71.0             160.0               163.0   
1123.json           19.0               3.0                 5.0   
9028.json            9.0              20.0                19.0   

            pants_on_fire_counts              context  \
id_json                                                 
2635.json                    0.0             a mailer   
10540.json                   0.0      a floor speech.   
324.json                     9.0               Denver   
1123.json                   44.0       a news release   
9028.json                    2.0  an interview on CNN   

                                                justification  
id_json                                                        
2635.json   That's a premise that he fails to back up. Ann...  
10540.json  Surovell said the decline of coal "started whe...  
324.json    Obama said he would have voted against the ame...  
1123.json   The release may have a point that Mikulskis co...  
9028.json   Crist said that the economic "turnaround start...

In [10]:
val_data.head()

label                                          statement  \
id_json                                                                      
12134.json  barely-true  We have less Americans working now than in the...   
238.json     pants-fire  When Obama was sworn into office, he DID NOT u...   
7891.json         false  Says Having organizations parading as being so...   
8169.json     half-true     Says nearly half of Oregons children are poor.   
929.json      half-true  On attacks by Republicans that various program...   

                                     subject          speaker  \
id_json                                                         
12134.json                      economy,jobs   vicky-hartzler   
238.json    obama-birth-certificate,religion      chain-email   
7891.json    campaign-finance,congress,taxes  earl-blumenauer   
8169.json                            poverty  jim-francesconi   
929.json                    economy,stimulus     barack-obama   

                                              speaker_job     state  \
id_json                                                               
12134.json                            U.S. Representative  Missouri   
238.json                                              NaN       NaN   
7891.json                             U.S. representative    Oregon   
8169.json   Member of the State Board of Higher Education    Oregon   
929.json                                        President  Illinois   

                 party  barely_true_counts  false_counts  half_true_counts  \
id_json                                                                      
12134.json  republican                   1             0                 1   
238.json          none                  11            43                 8   
7891.json     democrat                   0             1                 1   
8169.json         none                   0             1                 1   
929.json      democrat                  70            71               160   

            mostly_true_counts  pants_on_fire_counts  \
id_json                                                
12134.json                   0                     0   
238.json                     5                   105   
7891.json                    1                     0   
8169.json                    1                     0   
929.json                   163                     9   

                                  context  \
id_json                                     
12134.json   an interview with ABC17 News   
238.json                              NaN   
7891.json   a U.S. Ways and Means hearing   
8169.json              an opinion article   
929.json          interview with CBS News   

                                                justification  
id_json                                                        
12134.json  However, Hartzler was talking about the entire...  
238.json    Ellison used a Koran that once belonged to Tho...  
7891.json   However, we have two professors who say the la...  
8169.json   In fact, if you use federal definitions for po...  
929.json    Obama's point is that some perspective is in o...

In [11]:
test_data.head()

label                                          statement  \
id_json                                                                     
11972.json        true  Building a wall on the U.S.-Mexico border will...   
11685.json       false  Wisconsin is on pace to double the number of l...   
11096.json       false  Says John McCain has done nothing to help the ...   
5209.json    half-true  Suzanne Bonamici supports a plan that will cut...   
9524.json   pants-fire  When asked by a reporter whether hes at the ce...   

                                                      subject  \
id_json                                                         
11972.json                                        immigration   
11685.json                                               jobs   
11096.json                    military,veterans,voting-record   
5209.json   medicare,message-machine-2012,campaign-adverti...   
9524.json   campaign-finance,legal-issues,campaign-adverti...   

                                     speaker           speaker_job      state  \
id_json                                                                         
11972.json                        rick-perry              Governor      Texas   
11685.json                 katrina-shankland  State representative  Wisconsin   
11096.json                      donald-trump       President-Elect   New York   
5209.json                      rob-cornilles            consultant     Oregon   
9524.json   state-democratic-party-wisconsin                   NaN  Wisconsin   

                 party  barely_true_counts  false_counts  half_true_counts  \
id_json                                                                      
11972.json  republican                  30            30                42   
11685.json    democrat                   2             1                 0   
11096.json  republican                  63           114                51   
5209.json   republican                   1             1                 3   
9524.json     democrat                   5             7                 2   

            mostly_true_counts  pants_on_fire_counts  \
id_json                                                
11972.json                  23                    18   
11685.json                   0                     0   
11096.json                  37                    61   
5209.json                    1                     1   
9524.json                    2                     7   

                                 context  \
id_json                                    
11972.json               Radio interview   
11685.json             a news conference   
11096.json  comments on ABC's This Week.   
5209.json                   a radio show   
9524.json                    a web video   

                                                justification  
id_json                                                        
11972.json  Meantime, engineering experts agree the wall w...  
11685.json  She cited layoff notices received by the state...  
11096.json  Trump said that McCain "has done nothing to he...  
5209.json   But spending still goes up. In addition, many ...  
9524.json   Our rating A Democratic Party web video making...

In [12]:
print(train_data.shape, val_data.shape, test_data.shape)

(10242, 14) (1284, 14) (1267, 14)


In [13]:
data_na = pd.DataFrame(train_data.isnull().sum(), columns=['NAinTrain']).join(
    pd.DataFrame(val_data.isnull().sum(), columns=['NAinVal']).join(
        pd.DataFrame(test_data.isnull().sum(), columns=['NAinTest'])))

In [14]:
print(data_na)

                      NAinTrain  NAinVal  NAinTest
label                         2        0         0
statement                     2        0         0
subject                       4        0         0
speaker                       4        0         0
speaker_job                2899      345       325
state                      2210      279       262
party                         4        0         0
barely_true_counts            4        0         0
false_counts                  4        0         0
half_true_counts              4        0         0
mostly_true_counts            4        0         0
pants_on_fire_counts          4        0         0
context                     104       12        17
justification                88        4         9


In [15]:
# Dropping records where label in NA in Train 
train_data.dropna(subset=['label'],inplace=True)
# Viewing updated NA Dataframe 
data_na_1 = pd.DataFrame(train_data.isnull().sum(), columns=['NAinTrain']).join(
    pd.DataFrame(val_data.isnull().sum(), columns=['NAinVal']).join(
        pd.DataFrame(test_data.isnull().sum(), columns=['NAinTest'])))
print(data_na_1)

                      NAinTrain  NAinVal  NAinTest
label                         0        0         0
statement                     0        0         0
subject                       2        0         0
speaker                       2        0         0
speaker_job                2897      345       325
state                      2208      279       262
party                         2        0         0
barely_true_counts            2        0         0
false_counts                  2        0         0
half_true_counts              2        0         0
mostly_true_counts            2        0         0
pants_on_fire_counts          2        0         0
context                     102       12        17
justification                86        4         9


In [16]:
# Dropping Records where the all the count flags are NA in train data 
train_data.dropna(subset=['barely_true_counts'],inplace=True)
# Viewing Updated NA Dataframe 
data_na_2 = pd.DataFrame(train_data.isnull().sum(), columns=['NAinTrain']).join(
    pd.DataFrame(val_data.isnull().sum(), columns=['NAinVal']).join(
        pd.DataFrame(test_data.isnull().sum(), columns=['NAinTest'])))
print(data_na_2)

                      NAinTrain  NAinVal  NAinTest
label                         0        0         0
statement                     0        0         0
subject                       0        0         0
speaker                       0        0         0
speaker_job                2895      345       325
state                      2206      279       262
party                         0        0         0
barely_true_counts            0        0         0
false_counts                  0        0         0
half_true_counts              0        0         0
mostly_true_counts            0        0         0
pants_on_fire_counts          0        0         0
context                     100       12        17
justification                84        4         9


In [17]:
# Replacing all NA with "" (Empty space) speaker_job
train_data.speaker_job.fillna("", inplace=True)
val_data.speaker_job.fillna("", inplace=True)
test_data.speaker_job.fillna("", inplace=True)

In [18]:
# Replacing all NA with "" (Empty space) state
train_data.state.fillna("", inplace=True)
val_data.state.fillna("", inplace=True)
test_data.state.fillna("", inplace=True)

In [19]:
# Replacing all NA with "" (Empty space) Context
train_data.context.fillna("", inplace=True)
val_data.context.fillna("", inplace=True)
test_data.context.fillna("", inplace=True)

In [20]:
# Replacing all NA with "" (Empty space) Justification
train_data.justification.fillna("", inplace=True)
val_data.justification.fillna("", inplace=True)
test_data.justification.fillna("", inplace=True)

In [21]:
# Viewing Updated NA Dataframe 
data_na_3 = pd.DataFrame(train_data.isnull().sum(), columns=['NAinTrain']).join(
    pd.DataFrame(val_data.isnull().sum(), columns=['NAinVal']).join(
        pd.DataFrame(test_data.isnull().sum(), columns=['NAinTest'])))
print(data_na_3)

                      NAinTrain  NAinVal  NAinTest
label                         0        0         0
statement                     0        0         0
subject                       0        0         0
speaker                       0        0         0
speaker_job                   0        0         0
state                         0        0         0
party                         0        0         0
barely_true_counts            0        0         0
false_counts                  0        0         0
half_true_counts              0        0         0
mostly_true_counts            0        0         0
pants_on_fire_counts          0        0         0
context                       0        0         0
justification                 0        0         0


In [22]:
# Handling the State column anamolies 
train_data.loc[train_data.state.isin(['None', 'Unknown']), 'state'] = ''
train_data.loc[train_data.state.isin(['Tennesse']), 'state'] = 'Tennessee'
train_data.loc[train_data.state.isin(['PA - Pennsylvania']), 'state'] = 'Pennsylvania'
train_data.loc[train_data.state.isin(['Rhode island']), 'state'] = 'Rhode Island'
train_data.loc[train_data.state.isin(['Tex']), 'state'] = 'Texas'
train_data.loc[train_data.state.isin(['Virgiia','Virgina', 'Virginia director, Coalition to Stop Gun Violence']), 'state'] = 'Virginia'
train_data.loc[train_data.state.isin(['Washington D.C.','Washington DC','Washington state', 'Washington, D.C.',]), 'state'] = 'Washington'

val_data.loc[val_data.state.isin(['None', 'Unknown']), 'state'] = ''
val_data.loc[val_data.state.isin(['Tennesse']), 'state'] = 'Tennessee'
val_data.loc[val_data.state.isin(['PA - Pennsylvania']), 'state'] = 'Pennsylvania'
val_data.loc[val_data.state.isin(['Rhode island']), 'state'] = 'Rhode Island'
val_data.loc[val_data.state.isin(['Tex']), 'state'] = 'Texas'
val_data.loc[val_data.state.isin(['Virgiia','Virgina', 'Virginia director, Coalition to Stop Gun Violence']), 'state'] = 'Virginia'
val_data.loc[val_data.state.isin(['Washington D.C.','Washington DC','Washington state', 'Washington, D.C.',]), 'state'] = 'Washington'


val_data.loc[val_data.state.isin(['None', 'Unknown']), 'state'] = ''
val_data.loc[val_data.state.isin(['Tennesse']), 'state'] = 'Tennessee'
val_data.loc[val_data.state.isin(['PA - Pennsylvania']), 'state'] = 'Pennsylvania'
val_data.loc[val_data.state.isin(['Rhode island']), 'state'] = 'Rhode Island'
val_data.loc[val_data.state.isin(['Tex']), 'state'] = 'Texas'
val_data.loc[val_data.state.isin(['Virgiia','Virgina', 'Virginia director, Coalition to Stop Gun Violence']), 'state'] = 'Virginia'
val_data.loc[val_data.state.isin(['Washington D.C.','Washington DC','Washington state', 'Washington, D.C.',]), 'state'] = 'Washington'

In [24]:
train_data.to_csv("train2.csv")

In [24]:
train_data['Text'] = train_data['statement'].map(str) + train_data['justification'].map(str)
val_data['Text']   = val_data['statement'].map(str) + val_data['justification'].map(str)
test_data['Text']  = test_data['statement'].map(str) + test_data['justification'].map(str)

In [25]:
train_data = train_data.drop(labels=['statement','justification'],axis=1)
val_data   = val_data.drop(labels=['statement','justification'],axis=1)
test_data  = test_data.drop(labels=['statement','justification'],axis=1)

In [26]:
val_data['Text']

id_json
12134.json    We have less Americans working now than in the...
238.json      When Obama was sworn into office, he DID NOT u...
7891.json     Says Having organizations parading as being so...
8169.json     Says nearly half of Oregons children are poor....
929.json      On attacks by Republicans that various program...
                                    ...                        
3419.json     For the first time in more than a decade, impo...
12548.json    Says Donald Trump has bankrupted his companies...
401.json      John McCain and George Bush have "absolutely n...
1055.json     A new poll shows 62 percent support the presid...
9117.json     No one claims the report vindicating New Jerse...
Name: Text, Length: 1284, dtype: object

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [28]:
Y_train = le.fit_transform(train_data['label'])
Y_val   = le.fit_transform(val_data['label'])
Y_test  = le.fit_transform(test_data['label'])
#le.inverse_transform(Y_train)

In [29]:
#Test
#le.inverse_transform(Y_train)
#le.inverse_transform(Y_val)
#le.inverse_transform(Y_test)

In [30]:
X_train = train_data.drop(labels=['label'],axis=1)
X_val   = val_data.drop(labels=['label'],axis=1)
X_test  = test_data.drop(labels=['label'],axis=1)

In [31]:
print(" X Train Data ")
print(X_train.head())
print(" X Val Data ")
print(X_val.head())
print(" X Test Data ")
print(X_test.head())

 X Train Data 
                                       subject         speaker  \
id_json                                                          
2635.json                             abortion    dwayne-bohac   
10540.json  energy,history,job-accomplishments  scott-surovell   
324.json                        foreign-policy    barack-obama   
1123.json                          health-care    blog-posting   
9028.json                         economy,jobs   charlie-crist   

                     speaker_job     state       party  barely_true_counts  \
id_json                                                                      
2635.json   State representative     Texas  republican                 0.0   
10540.json        State delegate  Virginia    democrat                 0.0   
324.json               President  Illinois    democrat                70.0   
1123.json                                         none                 7.0   
9028.json                          Florida    democrat

In [32]:
print(" X Train Columns")
print(X_train.columns)
print(" X Val Columns ")
print(X_val.columns)
print(" X Test Columns ")
print(X_test.columns)

 X Train Columns
Index(['subject', 'speaker', 'speaker_job', 'state', 'party',
       'barely_true_counts', 'false_counts', 'half_true_counts',
       'mostly_true_counts', 'pants_on_fire_counts', 'context', 'Text'],
      dtype='object')
 X Val Columns 
Index(['subject', 'speaker', 'speaker_job', 'state', 'party',
       'barely_true_counts', 'false_counts', 'half_true_counts',
       'mostly_true_counts', 'pants_on_fire_counts', 'context', 'Text'],
      dtype='object')
 X Test Columns 
Index(['subject', 'speaker', 'speaker_job', 'state', 'party',
       'barely_true_counts', 'false_counts', 'half_true_counts',
       'mostly_true_counts', 'pants_on_fire_counts', 'context', 'Text'],
      dtype='object')


CONTRACTION_MAP = {
"ain't": "is not",
"aren't": "are not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he would",
"he'd've": "he would have",
"he'll": "he will",
"he'll've": "he he will have",
"he's": "he is",
"how'd": "how did",
"how'd'y": "how do you",
"how'll": "how will",
"how's": "how is",
"i'd": "i would",
"i'd've": "i would have",
"i'll": "i will",
"i'll've": "i will have",
"i'm": "i am",
"i've": "i have",
"isn't": "is not",
"it'd": "it would",
"it'd've": "it would have",
"it'll": "it will",
"it'll've": "it will have",
"it's": "it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"mightn't've": "might not have",
"must've": "must have",
"mustn't": "must not",
"mustn't've": "must not have",
"needn't": "need not",
"needn't've": "need not have",
"o'clock": "of the clock",
"oughtn't": "ought not",
"oughtn't've": "ought not have",
"shan't": "shall not",
"sha'n't": "shall not",
"shan't've": "shall not have",
"she'd": "she would",
"she'd've": "she would have",
"she'll": "she will",
"she'll've": "she will have",
"she's": "she is",
"should've": "should have",
"shouldn't": "should not",
"shouldn't've": "should not have",
"so've": "so have",
"so's": "so as",
"that'd": "that would",
"that'd've": "that would have",
"that's": "that is",
"there'd": "there would",
"there'd've": "there would have",
"there's": "there is",
"they'd": "they would",
"they'd've": "they would have",
"they'll": "they will",
"they'll've": "they will have",
"they're": "they are",
"they've": "they have",
"to've": "to have",
"wasn't": "was not",
"we'd": "we would",
"we'd've": "we would have",
"we'll": "we will",
"we'll've": "we will have",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
"what'll": "what will",
"what'll've": "what will have",
"what're": "what are",
"what's": "what is",
"what've": "what have",
"when's": "when is",
"when've": "when have",
"where'd": "where did",
"where's": "where is",
"where've": "where have",
"who'll": "who will",
"who'll've": "who will have",
"who's": "who is",
"who've": "who have",
"why's": "why is",
"why've": "why have",
"will've": "will have",
"won't": "will not",
"won't've": "will not have",
"would've": "would have",
"wouldn't": "would not",
"wouldn't've": "would not have",
"y'all": "you all",
"y'all'd": "you all would",
"y'all'd've": "you all would have",
"y'all're": "you all are",
"y'all've": "you all have",
"you'd": "you would",
"you'd've": "you would have",
"you'll": "you will",
"you'll've": "you will have",
"you're": "you are",
"you've": "you have",
}
# The code for expanding contraction words
def expand_contractions(text, contraction_mapping =  CONTRACTION_MAP):
    """expand shortened words to the actual form.
       e.g. don't to do not
    
       arguments:
            input_text: "text" of type "String".
         
       return:
            value: Text with expanded form of shorthened words.
        
       Example: 
       Input : ain't, aren't, can't, cause, can't've
       Output :  is not, are not, cannot, because, cannot have 
    
     """
    # Tokenizing text into tokens.
    list_Of_tokens = text.split(' ')

    # Checking for whether the given token matches with the Key & replacing word with key's value.
    
    # Check whether Word is in lidt_Of_tokens or not.
    for Word in list_Of_tokens: 
        # Check whether found word is in dictionary "Contraction Map" or not as a key. 
         if Word in CONTRACTION_MAP: 
                # If Word is present in both dictionary & list_Of_tokens, replace that word with the key value.
                list_Of_tokens = [item.replace(Word, CONTRACTION_MAP[Word]) for item in list_Of_tokens]
                
    # Converting list of tokens to String.
    String_Of_tokens = ' '.join(str(e) for e in list_Of_tokens) 
    return String_Of_tokens

In [34]:
#Punctuation deleting
#Lowercase + strip
#Numbers replacement with "NUM" token
#Extra whitespaces removing
txt_features = ['context', 'subject', 'speaker_job', 'Text']

for feature in txt_features:
    X_train[feature] = X_train[feature].str.replace(r'[^\w\s]+', ' ')
    X_train[feature] = X_train[feature].apply(lambda x: x.lower().strip())
    X_train[feature] = X_train[feature].str.replace('\w*\d+\w*','NUM')
    X_train[feature] = X_train[feature].str.replace('\s{2,}',' ')
    


for feature in txt_features:
    X_val[feature] = X_val[feature].str.replace(r'[^\w\s]+', ' ')
    X_val[feature] = X_val[feature].apply(lambda x: x.lower().strip())
    X_val[feature] = X_val[feature].str.replace('\w*\d+\w*','NUM')
    X_val[feature] = X_val[feature].str.replace('\s{2,}',' ')
    


for feature in txt_features:
    X_test[feature] = X_test[feature].str.replace(r'[^\w\s]+', ' ')
    X_test[feature] = X_test[feature].apply(lambda x: x.lower().strip())
    X_test[feature] = X_test[feature].str.replace('\w*\d+\w*','NUM')
    X_test[feature] = X_test[feature].str.replace('\s{2,}',' ')



C:\Users\rajup\AppData\Local\Temp/ipykernel_14288/3518861763.py:8: FutureWarning: The default value of regex will change from True to False in a future version.
  X_train[feature] = X_train[feature].str.replace(r'[^\w\s]+', ' ')
C:\Users\rajup\AppData\Local\Temp/ipykernel_14288/3518861763.py:10: FutureWarning: The default value of regex will change from True to False in a future version.
  X_train[feature] = X_train[feature].str.replace('\w*\d+\w*','NUM')
C:\Users\rajup\AppData\Local\Temp/ipykernel_14288/3518861763.py:11: FutureWarning: The default value of regex will change from True to False in a future version.
  X_train[feature] = X_train[feature].str.replace('\s{2,}',' ')
C:\Users\rajup\AppData\Local\Temp/ipykernel_14288/3518861763.py:16: FutureWarning: The default value of regex will change from True to False in a future version.
  X_val[feature] = X_val[feature].str.replace(r'[^\w\s]+', ' ')
C:\Users\rajup\AppData\Local\Temp/ipykernel_14288/3518861763.py:18: FutureWarning: The d

In [35]:
print(X_train['subject'].value_counts().nunique())
print(X_train['speaker'].value_counts().nunique())
print(X_train['speaker_job'].value_counts().nunique())
print(X_train['state'].value_counts().nunique())
print(X_train['party'].value_counts().nunique())
print(X_train['context'].value_counts().nunique())

56
58
58
42
18
59


In [36]:
# Label Encoding subject,speaker,speaker job, state and party
le_subj    = LabelEncoder()
le_spkr    = LabelEncoder()
le_spkr_jb = LabelEncoder()
le_state   = LabelEncoder()
le_prty    = LabelEncoder()
le_ctxt    = LabelEncoder()

X_train['subject'] = le_subj.fit_transform(X_train['subject'])
X_train['speaker']   = le_spkr.fit_transform(X_train['speaker'])
X_train['speaker_job']   = le_spkr_jb.fit_transform(X_train['speaker_job'])
X_train['state']   = le_state.fit_transform(X_train['state'])
X_train['party']   = le_prty.fit_transform(X_train['party'])
X_train['context']   = le_ctxt.fit_transform(X_train['context'])

X_val['subject'] = le_subj.fit_transform(X_val['subject'])
X_val['speaker']   = le_spkr.fit_transform(X_val['speaker'])
X_val['speaker_job']   = le_spkr_jb.fit_transform(X_val['speaker_job'])
X_val['state']   = le_state.fit_transform(X_val['state'])
X_val['party']   = le_prty.fit_transform(X_val['party'])
X_val['context']   = le_ctxt.fit_transform(X_val['context'])

X_test['subject'] = le_subj.fit_transform(X_test['subject'])
X_test['speaker']   = le_spkr.fit_transform(X_test['speaker'])
X_test['speaker_job']   = le_spkr_jb.fit_transform(X_test['speaker_job'])
X_test['state']   = le_state.fit_transform(X_test['state'])
X_test['party']   = le_prty.fit_transform(X_test['party'])
X_test['context']   = le_ctxt.fit_transform(X_test['context'])

In [37]:
print(" ----------------------- X Train Data ---------------------------- ")
print(X_train.head())
print(" ----------------------- X Val Data   ------------------------------")
print(X_val.head())
print(" ----------------------- X Test Data  ------------------------------")
print(X_test.head())

 ----------------------- X Train Data ---------------------------- 
            subject  speaker  speaker_job  state  party  barely_true_counts  \
id_json                                                                       
2635.json         2      814          954     58     19                 0.0   
10540.json     2570     2491          943     62      5                 0.0   
324.json       2862      182          722     20      5                70.0   
1123.json      3074      272            0      0     16                 7.0   
9028.json      2182      428            0     14      5                15.0   

            false_counts  half_true_counts  mostly_true_counts  \
id_json                                                          
2635.json            1.0               0.0                 0.0   
10540.json           0.0               1.0                 1.0   
324.json            71.0             160.0               163.0   
1123.json           19.0               3.0      

In [38]:
X_train_idx = X_train.index
X_val_idx   = X_val.index
X_test_idx  = X_test.index

In [39]:
X_test_idx

Index(['11972.json', '11685.json', '11096.json', '5209.json', '9524.json',
       '5962.json', '7070.json', '1046.json', '12849.json', '13270.json',
       ...
       '1005.json', '609.json', '9436.json', '5671.json', '6699.json',
       '7334.json', '9788.json', '10710.json', '3186.json', '6743.json'],
      dtype='object', name='id_json', length=1267)

In [40]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import  LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import learning_curve
from sklearn.metrics import confusion_matrix, f1_score, classification_report
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
from sklearn import svm
from sklearn import metrics

#from gensim.models.word2vec import Word2Vec

In [41]:
# Count Vectorizer Implementation 
# create a count vectorizer objec
count_vect = CountVectorizer(analyzer='word', token_pattern=r'\w{1,}',stop_words='english')
count_vect.fit(X_train['Text'])
# transform the training, testing and validation data using count vectorizer object
X_train_count =  count_vect.transform(X_train['Text'])
X_val_count   =  count_vect.transform(X_val['Text'])
X_test_count  =  count_vect.transform(X_test['Text'])

In [42]:
# TF IDF Implementation 
#
tfidf_vect = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', max_features=5000)
tfidf_vect.fit(X_train['Text'])
X_train_tfidf =  tfidf_vect.transform(X_train['Text'])
X_val_tfidf   =  tfidf_vect.transform(X_val['Text'])
X_test_tfidf  =  tfidf_vect.transform(X_test['Text'])

In [43]:
X_train_af = X_train[['subject', 'speaker', 'speaker_job', 'state', 'party',
       'barely_true_counts', 'false_counts', 'half_true_counts',
       'mostly_true_counts', 'pants_on_fire_counts', 'context']]

In [44]:
X_val_af = X_val[['subject', 'speaker', 'speaker_job', 'state', 'party',
       'barely_true_counts', 'false_counts', 'half_true_counts',
       'mostly_true_counts', 'pants_on_fire_counts', 'context']]

In [45]:
X_test_af = X_test[['subject', 'speaker', 'speaker_job', 'state', 'party',
       'barely_true_counts', 'false_counts', 'half_true_counts',
       'mostly_true_counts', 'pants_on_fire_counts', 'context']]

In [46]:
# Modelling
#naive bayes classifier
naive_bayes_classifier_count = MultinomialNB()
naive_bayes_classifier_count.fit(X_train_count, Y_train)

MultinomialNB()

In [47]:
# Predictions 
#predicted y
y_pred_val_count = naive_bayes_classifier_count.predict(X_val_count)
y_pred_test_count = naive_bayes_classifier_count.predict(X_test_count)

In [48]:
# Validation Metrics 
print(metrics.classification_report(Y_val, y_pred_val_count))
# Test Metrics 
print(metrics.classification_report(Y_test, y_pred_test_count))


              precision    recall  f1-score   support

           0       0.24      0.12      0.16       237
           1       0.25      0.27      0.26       263
           2       0.22      0.38      0.28       248
           3       0.30      0.35      0.32       251
           4       0.31      0.03      0.06       116
           5       0.21      0.19      0.20       169

    accuracy                           0.25      1284
   macro avg       0.25      0.22      0.21      1284
weighted avg       0.25      0.25      0.23      1284

              precision    recall  f1-score   support

           0       0.24      0.15      0.18       212
           1       0.23      0.23      0.23       249
           2       0.22      0.36      0.27       265
           3       0.19      0.19      0.19       241
           4       0.42      0.09      0.14        92
           5       0.18      0.16      0.17       208

    accuracy                           0.21      1267
   macro avg       0.25

In [49]:
# Naive Bayes with tfidf

naive_bayes_classifier_tfidf = MultinomialNB()
naive_bayes_classifier_tfidf.fit(X_train_tfidf, Y_train)

y_pred_val_tfidf = naive_bayes_classifier_tfidf.predict(X_val_tfidf)
y_pred_test_tfidf = naive_bayes_classifier_tfidf.predict(X_test_tfidf)

In [50]:
# Validation Metrics 
print(metrics.classification_report(Y_val, y_pred_val_tfidf))
# Test Metrics 
print(metrics.classification_report(Y_test, y_pred_test_tfidf))

              precision    recall  f1-score   support

           0       0.29      0.04      0.07       237
           1       0.28      0.35      0.31       263
           2       0.22      0.51      0.30       248
           3       0.26      0.31      0.28       251
           4       0.00      0.00      0.00       116
           5       0.22      0.05      0.08       169

    accuracy                           0.25      1284
   macro avg       0.21      0.21      0.17      1284
weighted avg       0.23      0.25      0.20      1284

              precision    recall  f1-score   support

           0       0.24      0.04      0.07       212
           1       0.23      0.29      0.26       249
           2       0.22      0.52      0.31       265
           3       0.21      0.23      0.22       241
           4       0.00      0.00      0.00        92
           5       0.33      0.06      0.10       208

    accuracy                           0.23      1267
   macro avg       0.20

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metr

In [51]:
# Merging additional features with vectors
X_train_af_count   =  X_train_af.merge(pd.DataFrame(X_train_count.toarray(),index=X_train_idx),left_index=True, right_index=True
)

X_val_af_count    =  X_val_af.merge(pd.DataFrame(X_val_count.toarray(),index=X_val_idx),left_index=True, right_index=True
)

X_test_af_count   =  X_test_af.merge(pd.DataFrame(X_test_count.toarray(),index=X_test_idx),left_index=True, right_index=True
)

X_train_af_tfidf  =  X_train_af.merge(pd.DataFrame(X_train_tfidf.toarray(),index=X_train_idx),left_index=True, right_index=True
)

X_val_af_tfidf    =  X_val_af.merge(pd.DataFrame(X_val_tfidf.toarray(),index=X_val_idx),left_index=True, right_index=True
)

X_test_af_tfidf   =  X_test_af.merge(pd.DataFrame(X_test_tfidf.toarray(),index=X_test_idx),left_index=True, right_index=True
)

In [52]:
X_val_af_tfidf

subject  speaker  speaker_job  state  party  barely_true_counts  \
id_json                                                                       
12134.json      343      646          267     23     14                   1   
238.json        665       79            0      0     12                  11   
7891.json        58      166          267     33      5                   0   
8169.json       678      285          154     33     12                   0   
929.json        366       36          188     13      5                  70   
...             ...      ...          ...    ...    ...                 ...   
3419.json       435       36          188     13      5                  70   
12548.json       72      240          202     28      5                  40   
401.json        543       73            0     43     12                   0   
1055.json       543       22            0      0     12                   1   
9117.json       103      550            8     28     14                   9   

            false_counts  half_true_counts  mostly_true_counts  \
id_json                                                          
12134.json             0                 1                   0   
238.json              43                 8                   5   
7891.json              1                 1                   1   
8169.json              1                 1                   1   
929.json              71               160                 163   
...                  ...               ...                 ...   
3419.json             71               160                 163   
12548.json            29                69                  76   
401.json               1                 0                   2   
1055.json              4                 4                   1   
9117.json             11                10                   7   

            pants_on_fire_counts  ...      4990  4991  4992  4993  4994  4995  \
id_json                           ...                                           
12134.json                     0  ...  0.000000   0.0   0.0   0.0   0.0   0.0   
238.json                     105  ...  0.000000   0.0   0.0   0.0   0.0   0.0   
7891.json                      0  ...  0.000000   0.0   0.0   0.0   0.0   0.0   
8169.json                      0  ...  0.068154   0.0   0.0   0.0   0.0   0.0   
929.json                       9  ...  0.085665   0.0   0.0   0.0   0.0   0.0   
...                          ...  ...       ...   ...   ...   ...   ...   ...   
3419.json                      9  ...  0.069787   0.0   0.0   0.0   0.0   0.0   
12548.json                     7  ...  0.000000   0.0   0.0   0.0   0.0   0.0   
401.json                       0  ...  0.000000   0.0   0.0   0.0   0.0   0.0   
1055.json                      0  ...  0.183598   0.0   0.0   0.0   0.0   0.0   
9117.json                      3  ...  0.000000   0.0   0.0   0.0   0.0   0.0   

            4996  4997  4998  4999  
id_json                             
12134.json   0.0   0.0   0.0   0.0  
238.json     0.0   0.0   0.0   0.0  
7891.json    0.0   0.0   0.0   0.0  
8169.json    0.0   0.0   0.0   0.0  
929.json     0.0   0.0   0.0   0.0  
...          ...   ...   ...   ...  
3419.json    0.0   0.0   0.0   0.0  
12548.json   0.0   0.0   0.0   0.0  
401.json     0.0   0.0   0.0   0.0  
1055.json    0.0   0.0   0.0   0.0  
9117.json    0.0   0.0   0.0   0.0  

[1284 rows x 5011 columns]

In [53]:
# Naive Bayes with count vector with additional features

naive_bayes_classifier_count_af = MultinomialNB()
naive_bayes_classifier_count_af.fit(X_train_af_count, Y_train)

y_pred_val_count_af    = naive_bayes_classifier_count_af.predict(X_val_af_count)
y_pred_test_count_af   = naive_bayes_classifier_count_af.predict(X_test_af_count)

In [54]:
# Validation Metrics 
print(metrics.classification_report(Y_val, y_pred_val_count_af))
# Test Metrics 
print(metrics.classification_report(Y_test, y_pred_test_count_af))

              precision    recall  f1-score   support

           0       0.21      0.16      0.18       237
           1       0.26      0.10      0.14       263
           2       0.21      0.09      0.13       248
           3       0.26      0.33      0.29       251
           4       0.17      0.51      0.25       116
           5       0.17      0.22      0.19       169

    accuracy                           0.21      1284
   macro avg       0.21      0.24      0.20      1284
weighted avg       0.22      0.21      0.19      1284

              precision    recall  f1-score   support

           0       0.15      0.11      0.13       212
           1       0.25      0.10      0.15       249
           2       0.25      0.12      0.16       265
           3       0.25      0.36      0.30       241
           4       0.14      0.48      0.22        92
           5       0.23      0.25      0.24       208

    accuracy                           0.21      1267
   macro avg       0.21

In [55]:
# Naive Bayes with tfidf with additional features 

In [56]:
naive_bayes_classifier_tfidf_af = MultinomialNB()
naive_bayes_classifier_tfidf_af.fit(X_train_af_tfidf, Y_train)

y_pred_val_tfidf_af    = naive_bayes_classifier_tfidf_af.predict(X_val_af_tfidf)
y_pred_test_tfidf_af   = naive_bayes_classifier_tfidf_af.predict(X_test_af_tfidf)

In [57]:
# Validation Metrics 
print("****************************  Validation Report  ********************************")
print(confusion_matrix(Y_val, y_pred_val_tfidf_af))
print(metrics.classification_report(Y_val, y_pred_val_tfidf_af))
# Test Metrics 
print("****************************  Test Report  **************************************")
print(confusion_matrix(Y_test, y_pred_test_tfidf_af))
print(metrics.classification_report(Y_test, y_pred_test_tfidf_af))


****************************  Validation Report  ********************************
[[34 24 18 44 71 46]
 [42 25 18 44 80 54]
 [30 22 20 60 55 61]
 [35 13 14 65 63 61]
 [10 16  7 13 53 17]
 [25 11 11 42 42 38]]
              precision    recall  f1-score   support

           0       0.19      0.14      0.16       237
           1       0.23      0.10      0.13       263
           2       0.23      0.08      0.12       248
           3       0.24      0.26      0.25       251
           4       0.15      0.46      0.22       116
           5       0.14      0.22      0.17       169

    accuracy                           0.18      1284
   macro avg       0.20      0.21      0.18      1284
weighted avg       0.20      0.18      0.17      1284

****************************  Test Report  **************************************
[[21 17 20 37 73 44]
 [41 34 28 39 62 45]
 [32 19 32 71 56 55]
 [29 19 18 67 50 58]
 [13  9  3 11 42 14]
 [29 13 15 58 39 54]]
              precision    recall  f1-s

In [58]:
# Decision Tree TPOT Pipeline given parameters from Count Vectorizer with af
from sklearn.tree import DecisionTreeClassifier
dt_count_af = DecisionTreeClassifier(criterion="entropy", max_depth=6, min_samples_leaf=1, min_samples_split=16)
dt_count_af.fit(X_train_af_count, Y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=6, min_samples_split=16)

In [59]:
y_pred_val_dt_count_af    = dt_count_af.predict(X_val_af_count)
y_pred_test_dt_count_af   = dt_count_af.predict(X_test_af_count)

In [60]:
# Validation Metrics 
print("****************************  Validation Report  ********************************")
print(confusion_matrix(Y_val, y_pred_val_dt_count_af))
print(metrics.classification_report(Y_val, y_pred_val_dt_count_af))
# Test Metrics 
print("****************************  Test Report  **************************************")
print(confusion_matrix(Y_test, y_pred_test_dt_count_af))
print(metrics.classification_report(Y_test, y_pred_test_dt_count_af))

****************************  Validation Report  ********************************
[[ 45  86  17  79  10   0]
 [  0 146   1  96  20   0]
 [  0  53  70 113  11   1]
 [  8  40  11 184   8   0]
 [  0  33   0  26  55   2]
 [  4  48   9  70   6  32]]
              precision    recall  f1-score   support

           0       0.79      0.19      0.31       237
           1       0.36      0.56      0.44       263
           2       0.65      0.28      0.39       248
           3       0.32      0.73      0.45       251
           4       0.50      0.47      0.49       116
           5       0.91      0.19      0.31       169

    accuracy                           0.41      1284
   macro avg       0.59      0.40      0.40      1284
weighted avg       0.57      0.41      0.39      1284

****************************  Test Report  **************************************
[[ 45  71  11  72  12   1]
 [  0 143   1  85  17   3]
 [  1  60  56 136  10   2]
 [  6  38  13 179   5   0]
 [  1  33   1   8  48 

In [61]:
# Decision Tree TPOT Pipeline given parameters from tfidf with af
from sklearn.tree import DecisionTreeClassifier
dt_tfidf_af = DecisionTreeClassifier(criterion="entropy", max_depth=6, min_samples_leaf=1, min_samples_split=16)
dt_tfidf_af.fit(X_train_af_tfidf, Y_train)


DecisionTreeClassifier(criterion='entropy', max_depth=6, min_samples_split=16)

In [62]:
y_pred_val_dt_tfidf_af    = dt_tfidf_af.predict(X_val_af_tfidf)
y_pred_test_dt_tfidf_af   = dt_tfidf_af.predict(X_test_af_tfidf)

In [63]:
# Having Labels instead of Label Encoding 
Y_test_inv = le.inverse_transform(Y_test)
Y_val_inv = le.inverse_transform(Y_val)
y_pred_val_dt_count_af_inv = le.inverse_transform(y_pred_val_dt_count_af)
y_pred_test_dt_count_af_inv = le.inverse_transform(y_pred_test_dt_count_af)

In [64]:
# Validation Metrics 
print("****************************  Validation Report  ********************************")
print(confusion_matrix(Y_val_inv, y_pred_val_dt_count_af_inv))
print(metrics.classification_report(Y_val_inv, y_pred_val_dt_count_af_inv))
# Test Metrics 
print("****************************  Test Report  **************************************")
print(confusion_matrix(Y_test_inv, y_pred_test_dt_count_af_inv))
print(metrics.classification_report(Y_test_inv, y_pred_test_dt_count_af_inv))

****************************  Validation Report  ********************************
[[ 45  86  17  79  10   0]
 [  0 146   1  96  20   0]
 [  0  53  70 113  11   1]
 [  8  40  11 184   8   0]
 [  0  33   0  26  55   2]
 [  4  48   9  70   6  32]]
              precision    recall  f1-score   support

 barely-true       0.79      0.19      0.31       237
       false       0.36      0.56      0.44       263
   half-true       0.65      0.28      0.39       248
 mostly-true       0.32      0.73      0.45       251
  pants-fire       0.50      0.47      0.49       116
        true       0.91      0.19      0.31       169

    accuracy                           0.41      1284
   macro avg       0.59      0.40      0.40      1284
weighted avg       0.57      0.41      0.39      1284

****************************  Test Report  **************************************
[[ 45  71  11  72  12   1]
 [  0 143   1  85  17   3]
 [  1  60  56 136  10   2]
 [  6  38  13 179   5   0]
 [  1  33   1   8  48 

In [65]:
# Having Labels instead of Label Encoding 
Y_test_inv = le.inverse_transform(Y_test)
Y_val_inv = le.inverse_transform(Y_val)
y_pred_val_dt_tfidf_af_inv = le.inverse_transform(y_pred_val_dt_tfidf_af)
y_pred_test_dt_tfidf_af_inv = le.inverse_transform(y_pred_test_dt_tfidf_af)

In [66]:
# Validation Metrics 
print("****************************  Validation Report  ********************************")
print(metrics.classification_report(Y_val_inv, y_pred_val_dt_tfidf_af_inv))
# Test Metrics 
print("****************************  Test Report  **************************************")
print(metrics.classification_report(Y_test_inv, y_pred_test_dt_tfidf_af_inv))

****************************  Validation Report  ********************************
              precision    recall  f1-score   support

 barely-true       0.66      0.27      0.39       237
       false       0.36      0.56      0.44       263
   half-true       0.72      0.24      0.36       248
 mostly-true       0.33      0.74      0.45       251
  pants-fire       0.51      0.42      0.46       116
        true       0.94      0.19      0.32       169

    accuracy                           0.42      1284
   macro avg       0.59      0.40      0.40      1284
weighted avg       0.57      0.42      0.40      1284

****************************  Test Report  **************************************
              precision    recall  f1-score   support

 barely-true       0.62      0.26      0.37       212
       false       0.37      0.56      0.44       249
   half-true       0.59      0.18      0.28       265
 mostly-true       0.31      0.74      0.44       241
  pants-fire       0.4

In [67]:
# Testing pytorch GPU 
import torch

torch.cuda.is_available()

True

In [68]:
# Checking GPU 
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 2060'

In [69]:
#!pip install TPOT

In [74]:
Y_train

array([1, 2, 3, ..., 2, 1, 4])

In [70]:
from tpot import TPOTClassifier
from sklearn.model_selection import RepeatedStratifiedKFold


In [71]:
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [72]:
# Tune Generations or max_time_mins for the pipeline
tpot = TPOTClassifier(max_time_mins=20, population_size=50, verbosity=2, random_state=42, cv= cv, scoring='accuracy', config_dict ='TPOT NN', warm_start=True)
tpot.fit(X_train_af_count, Y_train)
print(tpot.score(X_test_af_count, Y_test))

Optimization Progress:   0%|          | 0/50 [00:00<?, ?pipeline/s]



TPOT closed during evaluation in one generation.


TPOT closed prematurely. Will use the current best pipeline.


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"
C:\ProgramData\Anaconda3\lib\site-packag

RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly. If you enabled PyTorch estimators, please check the data requirements in the online documentation: https://epistasislab.github.io/tpot/using/

In [ ]:
print(tpot.score(X_test_af_count, Y_test))

In [ ]:
print(tpot.score(X_val_af_count, Y_val))

In [73]:
tpot.export('tpot_test_sample.py')

RuntimeError: A pipeline has not yet been optimized. Please call fit() first.

In [ ]:
os.getcwd()

In [ ]:
# Implemenation of TFIDF with TPOT

In [ ]:
tpot_tfidf = TPOTClassifier(max_time_mins=150, population_size=50, verbosity=3, random_state=42, cv= cv, scoring='accuracy', config_dict ='TPOT NN', warm_start=True,n_jobs=8)
tpot_tfidf.fit(X_train_af_tfidf, Y_train)
print(tpot_tfidf.score(X_test_af_tfidf, Y_test))

In [ ]:
tpot_tfidf.export('tpot_exported_pipeline_tfidf.py')

In [ ]:
# Glove Vectors
import os
import tqdm
import requests
import zipfile
URL = "http://nlp.stanford.edu/data/glove.42B.300d.zip"

In [ ]:
def download_extract_data(web_url=URL, target_file='glove.zip', delete_zip=False):
    #if the dataset already exists exit
    if os.path.isfile(target_file):
        print("datasets already downloded :) ")
        return

    
    print("**************************")
    print("  Downloading zip file")
    print("  >_<  Please wait >_< ")
    print("**************************")
    response = requests.get(web_url, stream=True)
    #read chunk by chunk
    handle = open(target_file, "wb")
    for chunk in tqdm.tqdm(response.iter_content(chunk_size=512)):
        if chunk:  
            handle.write(chunk)
    handle.close()  
    print("  Download completed ;) :") 
    #extract zip_file
    zf = zipfile.ZipFile(target_file)
    print("1. Extracting {} file".format(target_file))
    zf.extractall()
    if delete_zip:
        print("2. Deleting {} file".format(dataset_name+".zip"))
        os.remove(path=zip_file)

download_extract_data(URL)

In [ ]:
glove_file = 'glove.42B.300d.txt'

In [ ]:
!pip install gensim

In [ ]:
os.getcwd()

In [ ]:
#sample change 